# --- Project Info ---
sonar.projectKey=AlphaSweater_Security-Bank-Portal_a33b8b1d-e735-486b-85c0-0601eb6fb937
sonar.projectName=Security Bank Portal

# --- Sources ---
sonar.sources=server/src,client/src

# --- Coverage ---
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info
sonar.coverage.inclusions=server/src/services/**,server/src/models/**,server/src/middlewares/**

# --- Exclusions ---
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
