sonar.projectKey=AlphaSweater_Security-Bank-Portal_94638b9b-0971-4245-9ccc-d44d1b4fe252
sonar.projectName=Security Bank Portal

# Sources
sonar.sources=client/src,server/src

# Tests
sonar.tests=client/tests,server/tests
sonar.test.inclusions=**/*test*,**/*spec*

# Ignore generated & deps
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

# Coverage (LCOV from Vitest/Jest/Nyc)
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info,server/coverage/lcov.info
