# --- Project Info ---
sonar.projectKey=AlphaSweater_Security-Bank-Portal_94638b9b-0971-4245-9ccc-d44d1b4fe252
sonar.projectName=Security Bank Portal

# --- Sources ---
sonar.sources=server/src,client/src

# --- Coverage ---
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info
sonar.coverage.inclusions=server/src/services/**,server/src/models/**,server/src/middlewares/**

# --- Exclusions (ignore junk + build outputs) ---
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
